create table excel_arutetel(
    "id" serial primary key,
    "tetelszam" varchar(18),
    "nev" varchar(255) not null,
    "ar" integer,
    "mertekegyseg_id" integer not null references mertekegyseg("id"),
    "kozos" boolean not null default false,
    "uzletag" integer,
    "beszerzo" varchar(255),
    "besorolas" varchar(255),
    "keretszerzodes" varchar(255),
    "kerekites" varchar(255),
    "helyszinreelozetes1" varchar(255),
    "helyszinreelozetes2" varchar(255),
    "utanpotlasiido" varchar(255),
    "cikkszam" varchar(18) not null unique,
    "suly" float,
    "arutetelproblema" integer,
    "passziv" boolean not null default false
);